// Search Service gRPC Definition
// This file is the single source of truth for search-service API
// Copy to: biz-service/src/main/proto/, search-service/proto/

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: search_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchJobsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                            // Search keywords
	Locations       []string               `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"`                                    // Location filters
	Industries      []string               `protobuf:"bytes,3,rep,name=industries,proto3" json:"industries,omitempty"`                                  // Industry filters
	ExperienceLevel string                 `protobuf:"bytes,4,opt,name=experience_level,json=experienceLevel,proto3" json:"experience_level,omitempty"` // "entry", "mid", "senior", "lead"
	SalaryRange     string                 `protobuf:"bytes,5,opt,name=salary_range,json=salaryRange,proto3" json:"salary_range,omitempty"`             // "0-10k", "10k-20k", "20k-50k", "50k+"
	EmploymentType  string                 `protobuf:"bytes,6,opt,name=employment_type,json=employmentType,proto3" json:"employment_type,omitempty"`    // "full-time", "part-time", "contract"
	Page            int32                  `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`                                             // 1-based page number
	PageSize        int32                  `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                     // Items per page (max 50)
	SortBy          string                 `protobuf:"bytes,9,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`                            // "relevance", "date", "salary"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchJobsRequest) Reset() {
	*x = SearchJobsRequest{}
	mi := &file_search_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchJobsRequest) ProtoMessage() {}

func (x *SearchJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchJobsRequest.ProtoReflect.Descriptor instead.
func (*SearchJobsRequest) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{0}
}

func (x *SearchJobsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchJobsRequest) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *SearchJobsRequest) GetIndustries() []string {
	if x != nil {
		return x.Industries
	}
	return nil
}

func (x *SearchJobsRequest) GetExperienceLevel() string {
	if x != nil {
		return x.ExperienceLevel
	}
	return ""
}

func (x *SearchJobsRequest) GetSalaryRange() string {
	if x != nil {
		return x.SalaryRange
	}
	return ""
}

func (x *SearchJobsRequest) GetEmploymentType() string {
	if x != nil {
		return x.EmploymentType
	}
	return ""
}

func (x *SearchJobsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchJobsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type SearchJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	Facets        []*Facet               `protobuf:"bytes,5,rep,name=facets,proto3" json:"facets,omitempty"` // Aggregation facets
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchJobsResponse) Reset() {
	*x = SearchJobsResponse{}
	mi := &file_search_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchJobsResponse) ProtoMessage() {}

func (x *SearchJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchJobsResponse.ProtoReflect.Descriptor instead.
func (*SearchJobsResponse) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{1}
}

func (x *SearchJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *SearchJobsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchJobsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchJobsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *SearchJobsResponse) GetFacets() []*Facet {
	if x != nil {
		return x.Facets
	}
	return nil
}

type Job struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Company        string                 `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	CompanyLogo    string                 `protobuf:"bytes,4,opt,name=company_logo,json=companyLogo,proto3" json:"company_logo,omitempty"`
	Location       string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	SalaryRange    string                 `protobuf:"bytes,6,opt,name=salary_range,json=salaryRange,proto3" json:"salary_range,omitempty"`
	Experience     string                 `protobuf:"bytes,7,opt,name=experience,proto3" json:"experience,omitempty"`
	EmploymentType string                 `protobuf:"bytes,8,opt,name=employment_type,json=employmentType,proto3" json:"employment_type,omitempty"`
	Description    string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Requirements   []string               `protobuf:"bytes,10,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Benefits       []string               `protobuf:"bytes,11,rep,name=benefits,proto3" json:"benefits,omitempty"`
	PostedAt       string                 `protobuf:"bytes,12,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"` // ISO timestamp
	Source         string                 `protobuf:"bytes,13,opt,name=source,proto3" json:"source,omitempty"`                     // "boss", "lagou", "linkedin", "direct"
	SourceUrl      string                 `protobuf:"bytes,14,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	MatchScore     float64                `protobuf:"fixed64,15,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"` // 0-100 (only when matching)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_search_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{2}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Job) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Job) GetCompanyLogo() string {
	if x != nil {
		return x.CompanyLogo
	}
	return ""
}

func (x *Job) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Job) GetSalaryRange() string {
	if x != nil {
		return x.SalaryRange
	}
	return ""
}

func (x *Job) GetExperience() string {
	if x != nil {
		return x.Experience
	}
	return ""
}

func (x *Job) GetEmploymentType() string {
	if x != nil {
		return x.EmploymentType
	}
	return ""
}

func (x *Job) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Job) GetRequirements() []string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *Job) GetBenefits() []string {
	if x != nil {
		return x.Benefits
	}
	return nil
}

func (x *Job) GetPostedAt() string {
	if x != nil {
		return x.PostedAt
	}
	return ""
}

func (x *Job) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Job) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *Job) GetMatchScore() float64 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

type Facet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // "location", "industry", "experience"
	Items         []*FacetItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Facet) Reset() {
	*x = Facet{}
	mi := &file_search_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facet) ProtoMessage() {}

func (x *Facet) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facet.ProtoReflect.Descriptor instead.
func (*Facet) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{3}
}

func (x *Facet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Facet) GetItems() []*FacetItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type FacetItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacetItem) Reset() {
	*x = FacetItem{}
	mi := &file_search_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacetItem) ProtoMessage() {}

func (x *FacetItem) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacetItem.ProtoReflect.Descriptor instead.
func (*FacetItem) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{4}
}

func (x *FacetItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FacetItem) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resume        *ResumeProfile         `protobuf:"bytes,1,opt,name=resume,proto3" json:"resume,omitempty"`
	Job           *Job                   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchRequest) Reset() {
	*x = MatchRequest{}
	mi := &file_search_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRequest) ProtoMessage() {}

func (x *MatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRequest.ProtoReflect.Descriptor instead.
func (*MatchRequest) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{5}
}

func (x *MatchRequest) GetResume() *ResumeProfile {
	if x != nil {
		return x.Resume
	}
	return nil
}

func (x *MatchRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type ResumeProfile struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title              string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Skills             []string               `protobuf:"bytes,3,rep,name=skills,proto3" json:"skills,omitempty"`
	YearsExperience    int32                  `protobuf:"varint,4,opt,name=years_experience,json=yearsExperience,proto3" json:"years_experience,omitempty"`
	Experiences        []*WorkExperience      `protobuf:"bytes,5,rep,name=experiences,proto3" json:"experiences,omitempty"`
	PreferredLocations []string               `protobuf:"bytes,6,rep,name=preferred_locations,json=preferredLocations,proto3" json:"preferred_locations,omitempty"`
	ExpectedSalary     string                 `protobuf:"bytes,7,opt,name=expected_salary,json=expectedSalary,proto3" json:"expected_salary,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResumeProfile) Reset() {
	*x = ResumeProfile{}
	mi := &file_search_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeProfile) ProtoMessage() {}

func (x *ResumeProfile) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeProfile.ProtoReflect.Descriptor instead.
func (*ResumeProfile) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{6}
}

func (x *ResumeProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResumeProfile) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResumeProfile) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ResumeProfile) GetYearsExperience() int32 {
	if x != nil {
		return x.YearsExperience
	}
	return 0
}

func (x *ResumeProfile) GetExperiences() []*WorkExperience {
	if x != nil {
		return x.Experiences
	}
	return nil
}

func (x *ResumeProfile) GetPreferredLocations() []string {
	if x != nil {
		return x.PreferredLocations
	}
	return nil
}

func (x *ResumeProfile) GetExpectedSalary() string {
	if x != nil {
		return x.ExpectedSalary
	}
	return ""
}

type WorkExperience struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Company        string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	DurationMonths int32                  `protobuf:"varint,3,opt,name=duration_months,json=durationMonths,proto3" json:"duration_months,omitempty"`
	SkillsUsed     []string               `protobuf:"bytes,4,rep,name=skills_used,json=skillsUsed,proto3" json:"skills_used,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkExperience) Reset() {
	*x = WorkExperience{}
	mi := &file_search_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkExperience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkExperience) ProtoMessage() {}

func (x *WorkExperience) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkExperience.ProtoReflect.Descriptor instead.
func (*WorkExperience) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{7}
}

func (x *WorkExperience) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WorkExperience) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *WorkExperience) GetDurationMonths() int32 {
	if x != nil {
		return x.DurationMonths
	}
	return 0
}

func (x *WorkExperience) GetSkillsUsed() []string {
	if x != nil {
		return x.SkillsUsed
	}
	return nil
}

type MatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverallScore  float64                `protobuf:"fixed64,1,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"` // 0-100
	Details       *MatchDetails          `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	MatchReasons  []string               `protobuf:"bytes,3,rep,name=match_reasons,json=matchReasons,proto3" json:"match_reasons,omitempty"`
	GapReasons    []string               `protobuf:"bytes,4,rep,name=gap_reasons,json=gapReasons,proto3" json:"gap_reasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResponse) Reset() {
	*x = MatchResponse{}
	mi := &file_search_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResponse) ProtoMessage() {}

func (x *MatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResponse.ProtoReflect.Descriptor instead.
func (*MatchResponse) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{8}
}

func (x *MatchResponse) GetOverallScore() float64 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *MatchResponse) GetDetails() *MatchDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *MatchResponse) GetMatchReasons() []string {
	if x != nil {
		return x.MatchReasons
	}
	return nil
}

func (x *MatchResponse) GetGapReasons() []string {
	if x != nil {
		return x.GapReasons
	}
	return nil
}

type MatchDetails struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SkillMatch      float64                `protobuf:"fixed64,1,opt,name=skill_match,json=skillMatch,proto3" json:"skill_match,omitempty"`                // Skill match percentage
	ExperienceMatch float64                `protobuf:"fixed64,2,opt,name=experience_match,json=experienceMatch,proto3" json:"experience_match,omitempty"` // Experience match percentage
	LocationMatch   float64                `protobuf:"fixed64,3,opt,name=location_match,json=locationMatch,proto3" json:"location_match,omitempty"`       // Location match percentage
	SalaryMatch     float64                `protobuf:"fixed64,4,opt,name=salary_match,json=salaryMatch,proto3" json:"salary_match,omitempty"`             // Salary match percentage
	TitleMatch      float64                `protobuf:"fixed64,5,opt,name=title_match,json=titleMatch,proto3" json:"title_match,omitempty"`                // Title relevance
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchDetails) Reset() {
	*x = MatchDetails{}
	mi := &file_search_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchDetails) ProtoMessage() {}

func (x *MatchDetails) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchDetails.ProtoReflect.Descriptor instead.
func (*MatchDetails) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{9}
}

func (x *MatchDetails) GetSkillMatch() float64 {
	if x != nil {
		return x.SkillMatch
	}
	return 0
}

func (x *MatchDetails) GetExperienceMatch() float64 {
	if x != nil {
		return x.ExperienceMatch
	}
	return 0
}

func (x *MatchDetails) GetLocationMatch() float64 {
	if x != nil {
		return x.LocationMatch
	}
	return 0
}

func (x *MatchDetails) GetSalaryMatch() float64 {
	if x != nil {
		return x.SalaryMatch
	}
	return 0
}

func (x *MatchDetails) GetTitleMatch() float64 {
	if x != nil {
		return x.TitleMatch
	}
	return 0
}

type BatchMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resume        *ResumeProfile         `protobuf:"bytes,1,opt,name=resume,proto3" json:"resume,omitempty"`
	JobIds        []string               `protobuf:"bytes,2,rep,name=job_ids,json=jobIds,proto3" json:"job_ids,omitempty"` // Max 100 job IDs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMatchRequest) Reset() {
	*x = BatchMatchRequest{}
	mi := &file_search_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMatchRequest) ProtoMessage() {}

func (x *BatchMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMatchRequest.ProtoReflect.Descriptor instead.
func (*BatchMatchRequest) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{10}
}

func (x *BatchMatchRequest) GetResume() *ResumeProfile {
	if x != nil {
		return x.Resume
	}
	return nil
}

func (x *BatchMatchRequest) GetJobIds() []string {
	if x != nil {
		return x.JobIds
	}
	return nil
}

type BatchMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*JobMatch            `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	Processed     int32                  `protobuf:"varint,2,opt,name=processed,proto3" json:"processed,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMatchResponse) Reset() {
	*x = BatchMatchResponse{}
	mi := &file_search_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMatchResponse) ProtoMessage() {}

func (x *BatchMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMatchResponse.ProtoReflect.Descriptor instead.
func (*BatchMatchResponse) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{11}
}

func (x *BatchMatchResponse) GetMatches() []*JobMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *BatchMatchResponse) GetProcessed() int32 {
	if x != nil {
		return x.Processed
	}
	return 0
}

func (x *BatchMatchResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

type JobMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Details       *MatchDetails          `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobMatch) Reset() {
	*x = JobMatch{}
	mi := &file_search_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobMatch) ProtoMessage() {}

func (x *JobMatch) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobMatch.ProtoReflect.Descriptor instead.
func (*JobMatch) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{12}
}

func (x *JobMatch) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobMatch) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *JobMatch) GetDetails() *MatchDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type RecommendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Resume        *ResumeProfile         `protobuf:"bytes,2,opt,name=resume,proto3" json:"resume,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                       // Max results (default 10)
	ExcludeJobIds []string               `protobuf:"bytes,4,rep,name=exclude_job_ids,json=excludeJobIds,proto3" json:"exclude_job_ids,omitempty"` // Previously viewed jobs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_search_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{13}
}

func (x *RecommendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecommendRequest) GetResume() *ResumeProfile {
	if x != nil {
		return x.Resume
	}
	return nil
}

func (x *RecommendRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RecommendRequest) GetExcludeJobIds() []string {
	if x != nil {
		return x.ExcludeJobIds
	}
	return nil
}

type RecommendResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*RecommendedJob      `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_search_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{14}
}

func (x *RecommendResponse) GetRecommendations() []*RecommendedJob {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type RecommendedJob struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Job             *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	MatchScore      float64                `protobuf:"fixed64,2,opt,name=match_score,json=matchScore,proto3" json:"match_score,omitempty"`
	RecommendReason string                 `protobuf:"bytes,3,opt,name=recommend_reason,json=recommendReason,proto3" json:"recommend_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecommendedJob) Reset() {
	*x = RecommendedJob{}
	mi := &file_search_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendedJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedJob) ProtoMessage() {}

func (x *RecommendedJob) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedJob.ProtoReflect.Descriptor instead.
func (*RecommendedJob) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{15}
}

func (x *RecommendedJob) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *RecommendedJob) GetMatchScore() float64 {
	if x != nil {
		return x.MatchScore
	}
	return 0
}

func (x *RecommendedJob) GetRecommendReason() string {
	if x != nil {
		return x.RecommendReason
	}
	return ""
}

type SuggestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"` // Partial input text
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`  // Max suggestions (default 5)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionRequest) Reset() {
	*x = SuggestionRequest{}
	mi := &file_search_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionRequest) ProtoMessage() {}

func (x *SuggestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionRequest.ProtoReflect.Descriptor instead.
func (*SuggestionRequest) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{16}
}

func (x *SuggestionRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *SuggestionRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SuggestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []*Suggestion          `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionResponse) Reset() {
	*x = SuggestionResponse{}
	mi := &file_search_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionResponse) ProtoMessage() {}

func (x *SuggestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionResponse.ProtoReflect.Descriptor instead.
func (*SuggestionResponse) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{17}
}

func (x *SuggestionResponse) GetSuggestions() []*Suggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type Suggestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`    // "job_title", "company", "skill"
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"` // Number of matching jobs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Suggestion) Reset() {
	*x = Suggestion{}
	mi := &file_search_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Suggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suggestion) ProtoMessage() {}

func (x *Suggestion) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suggestion.ProtoReflect.Descriptor instead.
func (*Suggestion) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{18}
}

func (x *Suggestion) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Suggestion) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Suggestion) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TrendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"` // Optional location filter
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`      // Max items (default 10)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingRequest) Reset() {
	*x = TrendingRequest{}
	mi := &file_search_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingRequest) ProtoMessage() {}

func (x *TrendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingRequest.ProtoReflect.Descriptor instead.
func (*TrendingRequest) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{19}
}

func (x *TrendingRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *TrendingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TrendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TrendingItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingResponse) Reset() {
	*x = TrendingResponse{}
	mi := &file_search_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingResponse) ProtoMessage() {}

func (x *TrendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingResponse.ProtoReflect.Descriptor instead.
func (*TrendingResponse) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{20}
}

func (x *TrendingResponse) GetItems() []*TrendingItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type TrendingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	SearchCount   int32                  `protobuf:"varint,2,opt,name=search_count,json=searchCount,proto3" json:"search_count,omitempty"`
	GrowthRate    float64                `protobuf:"fixed64,3,opt,name=growth_rate,json=growthRate,proto3" json:"growth_rate,omitempty"` // Week-over-week growth
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingItem) Reset() {
	*x = TrendingItem{}
	mi := &file_search_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingItem) ProtoMessage() {}

func (x *TrendingItem) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingItem.ProtoReflect.Descriptor instead.
func (*TrendingItem) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{21}
}

func (x *TrendingItem) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *TrendingItem) GetSearchCount() int32 {
	if x != nil {
		return x.SearchCount
	}
	return 0
}

func (x *TrendingItem) GetGrowthRate() float64 {
	if x != nil {
		return x.GrowthRate
	}
	return 0
}

type CrawlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`       // "boss", "lagou", "all"
	Keywords      []string               `protobuf:"bytes,2,rep,name=keywords,proto3" json:"keywords,omitempty"`   // Search keywords to crawl
	Locations     []string               `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"` // Locations to crawl
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlRequest) Reset() {
	*x = CrawlRequest{}
	mi := &file_search_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlRequest) ProtoMessage() {}

func (x *CrawlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlRequest.ProtoReflect.Descriptor instead.
func (*CrawlRequest) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{22}
}

func (x *CrawlRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CrawlRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *CrawlRequest) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

type CrawlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "queued", "running", "completed", "failed"
	EstimatedJobs int32                  `protobuf:"varint,3,opt,name=estimated_jobs,json=estimatedJobs,proto3" json:"estimated_jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlResponse) Reset() {
	*x = CrawlResponse{}
	mi := &file_search_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlResponse) ProtoMessage() {}

func (x *CrawlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlResponse.ProtoReflect.Descriptor instead.
func (*CrawlResponse) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{23}
}

func (x *CrawlResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CrawlResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CrawlResponse) GetEstimatedJobs() int32 {
	if x != nil {
		return x.EstimatedJobs
	}
	return 0
}

type AnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`                        // "salary_trend", "demand_trend", "skill_trend"
	Industry      string                 `protobuf:"bytes,2,opt,name=industry,proto3" json:"industry,omitempty"`                    // Industry filter
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`                    // Location filter
	TimeRange     string                 `protobuf:"bytes,4,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"` // "7d", "30d", "90d", "1y"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsRequest) Reset() {
	*x = AnalyticsRequest{}
	mi := &file_search_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsRequest) ProtoMessage() {}

func (x *AnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsRequest.ProtoReflect.Descriptor instead.
func (*AnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{24}
}

func (x *AnalyticsRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *AnalyticsRequest) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *AnalyticsRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AnalyticsRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

type AnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPoints    []*DataPoint           `protobuf:"bytes,1,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	Summary       map[string]float64     `protobuf:"bytes,2,rep,name=summary,proto3" json:"summary,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // Key metrics summary
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticsResponse) Reset() {
	*x = AnalyticsResponse{}
	mi := &file_search_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsResponse) ProtoMessage() {}

func (x *AnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsResponse.ProtoReflect.Descriptor instead.
func (*AnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{25}
}

func (x *AnalyticsResponse) GetDataPoints() []*DataPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

func (x *AnalyticsResponse) GetSummary() map[string]float64 {
	if x != nil {
		return x.Summary
	}
	return nil
}

type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // ISO date
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_search_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_search_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_search_service_proto_rawDescGZIP(), []int{26}
}

func (x *DataPoint) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DataPoint) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

var File_search_service_proto protoreflect.FileDescriptor

const file_search_service_proto_rawDesc = "" +
	"\n" +
	"\x14search_service.proto\x12\fcvibe.search\"\xa8\x02\n" +
	"\x11SearchJobsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1c\n" +
	"\tlocations\x18\x02 \x03(\tR\tlocations\x12\x1e\n" +
	"\n" +
	"industries\x18\x03 \x03(\tR\n" +
	"industries\x12)\n" +
	"\x10experience_level\x18\x04 \x01(\tR\x0fexperienceLevel\x12!\n" +
	"\fsalary_range\x18\x05 \x01(\tR\vsalaryRange\x12'\n" +
	"\x0femployment_type\x18\x06 \x01(\tR\x0eemploymentType\x12\x12\n" +
	"\x04page\x18\a \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\b \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\t \x01(\tR\x06sortBy\"\xb3\x01\n" +
	"\x12SearchJobsResponse\x12%\n" +
	"\x04jobs\x18\x01 \x03(\v2\x11.cvibe.search.JobR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\x12+\n" +
	"\x06facets\x18\x05 \x03(\v2\x13.cvibe.search.FacetR\x06facets\"\xc7\x03\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x03 \x01(\tR\acompany\x12!\n" +
	"\fcompany_logo\x18\x04 \x01(\tR\vcompanyLogo\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12!\n" +
	"\fsalary_range\x18\x06 \x01(\tR\vsalaryRange\x12\x1e\n" +
	"\n" +
	"experience\x18\a \x01(\tR\n" +
	"experience\x12'\n" +
	"\x0femployment_type\x18\b \x01(\tR\x0eemploymentType\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\"\n" +
	"\frequirements\x18\n" +
	" \x03(\tR\frequirements\x12\x1a\n" +
	"\bbenefits\x18\v \x03(\tR\bbenefits\x12\x1b\n" +
	"\tposted_at\x18\f \x01(\tR\bpostedAt\x12\x16\n" +
	"\x06source\x18\r \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"source_url\x18\x0e \x01(\tR\tsourceUrl\x12\x1f\n" +
	"\vmatch_score\x18\x0f \x01(\x01R\n" +
	"matchScore\"J\n" +
	"\x05Facet\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x05items\x18\x02 \x03(\v2\x17.cvibe.search.FacetItemR\x05items\"7\n" +
	"\tFacetItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"h\n" +
	"\fMatchRequest\x123\n" +
	"\x06resume\x18\x01 \x01(\v2\x1b.cvibe.search.ResumeProfileR\x06resume\x12#\n" +
	"\x03job\x18\x02 \x01(\v2\x11.cvibe.search.JobR\x03job\"\x9b\x02\n" +
	"\rResumeProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06skills\x18\x03 \x03(\tR\x06skills\x12)\n" +
	"\x10years_experience\x18\x04 \x01(\x05R\x0fyearsExperience\x12>\n" +
	"\vexperiences\x18\x05 \x03(\v2\x1c.cvibe.search.WorkExperienceR\vexperiences\x12/\n" +
	"\x13preferred_locations\x18\x06 \x03(\tR\x12preferredLocations\x12'\n" +
	"\x0fexpected_salary\x18\a \x01(\tR\x0eexpectedSalary\"\x8a\x01\n" +
	"\x0eWorkExperience\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12'\n" +
	"\x0fduration_months\x18\x03 \x01(\x05R\x0edurationMonths\x12\x1f\n" +
	"\vskills_used\x18\x04 \x03(\tR\n" +
	"skillsUsed\"\xb0\x01\n" +
	"\rMatchResponse\x12#\n" +
	"\roverall_score\x18\x01 \x01(\x01R\foverallScore\x124\n" +
	"\adetails\x18\x02 \x01(\v2\x1a.cvibe.search.MatchDetailsR\adetails\x12#\n" +
	"\rmatch_reasons\x18\x03 \x03(\tR\fmatchReasons\x12\x1f\n" +
	"\vgap_reasons\x18\x04 \x03(\tR\n" +
	"gapReasons\"\xc5\x01\n" +
	"\fMatchDetails\x12\x1f\n" +
	"\vskill_match\x18\x01 \x01(\x01R\n" +
	"skillMatch\x12)\n" +
	"\x10experience_match\x18\x02 \x01(\x01R\x0fexperienceMatch\x12%\n" +
	"\x0elocation_match\x18\x03 \x01(\x01R\rlocationMatch\x12!\n" +
	"\fsalary_match\x18\x04 \x01(\x01R\vsalaryMatch\x12\x1f\n" +
	"\vtitle_match\x18\x05 \x01(\x01R\n" +
	"titleMatch\"a\n" +
	"\x11BatchMatchRequest\x123\n" +
	"\x06resume\x18\x01 \x01(\v2\x1b.cvibe.search.ResumeProfileR\x06resume\x12\x17\n" +
	"\ajob_ids\x18\x02 \x03(\tR\x06jobIds\"|\n" +
	"\x12BatchMatchResponse\x120\n" +
	"\amatches\x18\x01 \x03(\v2\x16.cvibe.search.JobMatchR\amatches\x12\x1c\n" +
	"\tprocessed\x18\x02 \x01(\x05R\tprocessed\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\"m\n" +
	"\bJobMatch\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x124\n" +
	"\adetails\x18\x03 \x01(\v2\x1a.cvibe.search.MatchDetailsR\adetails\"\x9e\x01\n" +
	"\x10RecommendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x123\n" +
	"\x06resume\x18\x02 \x01(\v2\x1b.cvibe.search.ResumeProfileR\x06resume\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12&\n" +
	"\x0fexclude_job_ids\x18\x04 \x03(\tR\rexcludeJobIds\"[\n" +
	"\x11RecommendResponse\x12F\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x1c.cvibe.search.RecommendedJobR\x0frecommendations\"\x81\x01\n" +
	"\x0eRecommendedJob\x12#\n" +
	"\x03job\x18\x01 \x01(\v2\x11.cvibe.search.JobR\x03job\x12\x1f\n" +
	"\vmatch_score\x18\x02 \x01(\x01R\n" +
	"matchScore\x12)\n" +
	"\x10recommend_reason\x18\x03 \x01(\tR\x0frecommendReason\"A\n" +
	"\x11SuggestionRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"P\n" +
	"\x12SuggestionResponse\x12:\n" +
	"\vsuggestions\x18\x01 \x03(\v2\x18.cvibe.search.SuggestionR\vsuggestions\"J\n" +
	"\n" +
	"Suggestion\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"C\n" +
	"\x0fTrendingRequest\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"D\n" +
	"\x10TrendingResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.cvibe.search.TrendingItemR\x05items\"l\n" +
	"\fTrendingItem\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12!\n" +
	"\fsearch_count\x18\x02 \x01(\x05R\vsearchCount\x12\x1f\n" +
	"\vgrowth_rate\x18\x03 \x01(\x01R\n" +
	"growthRate\"`\n" +
	"\fCrawlRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1a\n" +
	"\bkeywords\x18\x02 \x03(\tR\bkeywords\x12\x1c\n" +
	"\tlocations\x18\x03 \x03(\tR\tlocations\"g\n" +
	"\rCrawlResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0eestimated_jobs\x18\x03 \x01(\x05R\restimatedJobs\"\x81\x01\n" +
	"\x10AnalyticsRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x1a\n" +
	"\bindustry\x18\x02 \x01(\tR\bindustry\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1d\n" +
	"\n" +
	"time_range\x18\x04 \x01(\tR\ttimeRange\"\xd1\x01\n" +
	"\x11AnalyticsResponse\x128\n" +
	"\vdata_points\x18\x01 \x03(\v2\x17.cvibe.search.DataPointR\n" +
	"dataPoints\x12F\n" +
	"\asummary\x18\x02 \x03(\v2,.cvibe.search.AnalyticsResponse.SummaryEntryR\asummary\x1a:\n" +
	"\fSummaryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"K\n" +
	"\tDataPoint\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label2\xa3\x05\n" +
	"\rSearchService\x12O\n" +
	"\n" +
	"SearchJobs\x12\x1f.cvibe.search.SearchJobsRequest\x1a .cvibe.search.SearchJobsResponse\x12K\n" +
	"\x10MatchResumeToJob\x12\x1a.cvibe.search.MatchRequest\x1a\x1b.cvibe.search.MatchResponse\x12O\n" +
	"\n" +
	"BatchMatch\x12\x1f.cvibe.search.BatchMatchRequest\x1a .cvibe.search.BatchMatchResponse\x12X\n" +
	"\x15GetJobRecommendations\x12\x1e.cvibe.search.RecommendRequest\x1a\x1f.cvibe.search.RecommendResponse\x12Y\n" +
	"\x14GetSearchSuggestions\x12\x1f.cvibe.search.SuggestionRequest\x1a .cvibe.search.SuggestionResponse\x12T\n" +
	"\x13GetTrendingSearches\x12\x1d.cvibe.search.TrendingRequest\x1a\x1e.cvibe.search.TrendingResponse\x12G\n" +
	"\fTriggerCrawl\x12\x1a.cvibe.search.CrawlRequest\x1a\x1b.cvibe.search.CrawlResponse\x12O\n" +
	"\fGetAnalytics\x12\x1e.cvibe.search.AnalyticsRequest\x1a\x1f.cvibe.search.AnalyticsResponseBT\n" +
	"\x15com.cvibe.grpc.searchB\x12SearchServiceProtoP\x01Z%github.com/cvibe/search-service/protob\x06proto3"

var (
	file_search_service_proto_rawDescOnce sync.Once
	file_search_service_proto_rawDescData []byte
)

func file_search_service_proto_rawDescGZIP() []byte {
	file_search_service_proto_rawDescOnce.Do(func() {
		file_search_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_service_proto_rawDesc), len(file_search_service_proto_rawDesc)))
	})
	return file_search_service_proto_rawDescData
}

var file_search_service_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_search_service_proto_goTypes = []any{
	(*SearchJobsRequest)(nil),  // 0: cvibe.search.SearchJobsRequest
	(*SearchJobsResponse)(nil), // 1: cvibe.search.SearchJobsResponse
	(*Job)(nil),                // 2: cvibe.search.Job
	(*Facet)(nil),              // 3: cvibe.search.Facet
	(*FacetItem)(nil),          // 4: cvibe.search.FacetItem
	(*MatchRequest)(nil),       // 5: cvibe.search.MatchRequest
	(*ResumeProfile)(nil),      // 6: cvibe.search.ResumeProfile
	(*WorkExperience)(nil),     // 7: cvibe.search.WorkExperience
	(*MatchResponse)(nil),      // 8: cvibe.search.MatchResponse
	(*MatchDetails)(nil),       // 9: cvibe.search.MatchDetails
	(*BatchMatchRequest)(nil),  // 10: cvibe.search.BatchMatchRequest
	(*BatchMatchResponse)(nil), // 11: cvibe.search.BatchMatchResponse
	(*JobMatch)(nil),           // 12: cvibe.search.JobMatch
	(*RecommendRequest)(nil),   // 13: cvibe.search.RecommendRequest
	(*RecommendResponse)(nil),  // 14: cvibe.search.RecommendResponse
	(*RecommendedJob)(nil),     // 15: cvibe.search.RecommendedJob
	(*SuggestionRequest)(nil),  // 16: cvibe.search.SuggestionRequest
	(*SuggestionResponse)(nil), // 17: cvibe.search.SuggestionResponse
	(*Suggestion)(nil),         // 18: cvibe.search.Suggestion
	(*TrendingRequest)(nil),    // 19: cvibe.search.TrendingRequest
	(*TrendingResponse)(nil),   // 20: cvibe.search.TrendingResponse
	(*TrendingItem)(nil),       // 21: cvibe.search.TrendingItem
	(*CrawlRequest)(nil),       // 22: cvibe.search.CrawlRequest
	(*CrawlResponse)(nil),      // 23: cvibe.search.CrawlResponse
	(*AnalyticsRequest)(nil),   // 24: cvibe.search.AnalyticsRequest
	(*AnalyticsResponse)(nil),  // 25: cvibe.search.AnalyticsResponse
	(*DataPoint)(nil),          // 26: cvibe.search.DataPoint
	nil,                        // 27: cvibe.search.AnalyticsResponse.SummaryEntry
}
var file_search_service_proto_depIdxs = []int32{
	2,  // 0: cvibe.search.SearchJobsResponse.jobs:type_name -> cvibe.search.Job
	3,  // 1: cvibe.search.SearchJobsResponse.facets:type_name -> cvibe.search.Facet
	4,  // 2: cvibe.search.Facet.items:type_name -> cvibe.search.FacetItem
	6,  // 3: cvibe.search.MatchRequest.resume:type_name -> cvibe.search.ResumeProfile
	2,  // 4: cvibe.search.MatchRequest.job:type_name -> cvibe.search.Job
	7,  // 5: cvibe.search.ResumeProfile.experiences:type_name -> cvibe.search.WorkExperience
	9,  // 6: cvibe.search.MatchResponse.details:type_name -> cvibe.search.MatchDetails
	6,  // 7: cvibe.search.BatchMatchRequest.resume:type_name -> cvibe.search.ResumeProfile
	12, // 8: cvibe.search.BatchMatchResponse.matches:type_name -> cvibe.search.JobMatch
	9,  // 9: cvibe.search.JobMatch.details:type_name -> cvibe.search.MatchDetails
	6,  // 10: cvibe.search.RecommendRequest.resume:type_name -> cvibe.search.ResumeProfile
	15, // 11: cvibe.search.RecommendResponse.recommendations:type_name -> cvibe.search.RecommendedJob
	2,  // 12: cvibe.search.RecommendedJob.job:type_name -> cvibe.search.Job
	18, // 13: cvibe.search.SuggestionResponse.suggestions:type_name -> cvibe.search.Suggestion
	21, // 14: cvibe.search.TrendingResponse.items:type_name -> cvibe.search.TrendingItem
	26, // 15: cvibe.search.AnalyticsResponse.data_points:type_name -> cvibe.search.DataPoint
	27, // 16: cvibe.search.AnalyticsResponse.summary:type_name -> cvibe.search.AnalyticsResponse.SummaryEntry
	0,  // 17: cvibe.search.SearchService.SearchJobs:input_type -> cvibe.search.SearchJobsRequest
	5,  // 18: cvibe.search.SearchService.MatchResumeToJob:input_type -> cvibe.search.MatchRequest
	10, // 19: cvibe.search.SearchService.BatchMatch:input_type -> cvibe.search.BatchMatchRequest
	13, // 20: cvibe.search.SearchService.GetJobRecommendations:input_type -> cvibe.search.RecommendRequest
	16, // 21: cvibe.search.SearchService.GetSearchSuggestions:input_type -> cvibe.search.SuggestionRequest
	19, // 22: cvibe.search.SearchService.GetTrendingSearches:input_type -> cvibe.search.TrendingRequest
	22, // 23: cvibe.search.SearchService.TriggerCrawl:input_type -> cvibe.search.CrawlRequest
	24, // 24: cvibe.search.SearchService.GetAnalytics:input_type -> cvibe.search.AnalyticsRequest
	1,  // 25: cvibe.search.SearchService.SearchJobs:output_type -> cvibe.search.SearchJobsResponse
	8,  // 26: cvibe.search.SearchService.MatchResumeToJob:output_type -> cvibe.search.MatchResponse
	11, // 27: cvibe.search.SearchService.BatchMatch:output_type -> cvibe.search.BatchMatchResponse
	14, // 28: cvibe.search.SearchService.GetJobRecommendations:output_type -> cvibe.search.RecommendResponse
	17, // 29: cvibe.search.SearchService.GetSearchSuggestions:output_type -> cvibe.search.SuggestionResponse
	20, // 30: cvibe.search.SearchService.GetTrendingSearches:output_type -> cvibe.search.TrendingResponse
	23, // 31: cvibe.search.SearchService.TriggerCrawl:output_type -> cvibe.search.CrawlResponse
	25, // 32: cvibe.search.SearchService.GetAnalytics:output_type -> cvibe.search.AnalyticsResponse
	25, // [25:33] is the sub-list for method output_type
	17, // [17:25] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_search_service_proto_init() }
func file_search_service_proto_init() {
	if File_search_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_service_proto_rawDesc), len(file_search_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_service_proto_goTypes,
		DependencyIndexes: file_search_service_proto_depIdxs,
		MessageInfos:      file_search_service_proto_msgTypes,
	}.Build()
	File_search_service_proto = out.File
	file_search_service_proto_goTypes = nil
	file_search_service_proto_depIdxs = nil
}
