// Search Service gRPC Definition
// This file is the single source of truth for search-service API
// Copy to: biz-service/src/main/proto/, search-service/proto/

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: search_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchService_SearchJobs_FullMethodName            = "/cvibe.search.SearchService/SearchJobs"
	SearchService_MatchResumeToJob_FullMethodName      = "/cvibe.search.SearchService/MatchResumeToJob"
	SearchService_BatchMatch_FullMethodName            = "/cvibe.search.SearchService/BatchMatch"
	SearchService_GetJobRecommendations_FullMethodName = "/cvibe.search.SearchService/GetJobRecommendations"
	SearchService_GetSearchSuggestions_FullMethodName  = "/cvibe.search.SearchService/GetSearchSuggestions"
	SearchService_GetTrendingSearches_FullMethodName   = "/cvibe.search.SearchService/GetTrendingSearches"
	SearchService_TriggerCrawl_FullMethodName          = "/cvibe.search.SearchService/TriggerCrawl"
	SearchService_GetAnalytics_FullMethodName          = "/cvibe.search.SearchService/GetAnalytics"
)

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	// Job Search - Full-text search with filters
	SearchJobs(ctx context.Context, in *SearchJobsRequest, opts ...grpc.CallOption) (*SearchJobsResponse, error)
	// Resume-Job Matching - Calculate match score
	MatchResumeToJob(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error)
	// Batch Matching - Parallel matching for multiple jobs
	BatchMatch(ctx context.Context, in *BatchMatchRequest, opts ...grpc.CallOption) (*BatchMatchResponse, error)
	// Job Recommendations - Personalized job suggestions
	GetJobRecommendations(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error)
	// Search Suggestions - Autocomplete
	GetSearchSuggestions(ctx context.Context, in *SuggestionRequest, opts ...grpc.CallOption) (*SuggestionResponse, error)
	// Trending Searches - Popular searches
	GetTrendingSearches(ctx context.Context, in *TrendingRequest, opts ...grpc.CallOption) (*TrendingResponse, error)
	// Crawler Control - Trigger job crawling
	TriggerCrawl(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error)
	// Analytics - Market data aggregation
	GetAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) SearchJobs(ctx context.Context, in *SearchJobsRequest, opts ...grpc.CallOption) (*SearchJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchJobsResponse)
	err := c.cc.Invoke(ctx, SearchService_SearchJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) MatchResumeToJob(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchResponse)
	err := c.cc.Invoke(ctx, SearchService_MatchResumeToJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) BatchMatch(ctx context.Context, in *BatchMatchRequest, opts ...grpc.CallOption) (*BatchMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchMatchResponse)
	err := c.cc.Invoke(ctx, SearchService_BatchMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetJobRecommendations(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendResponse)
	err := c.cc.Invoke(ctx, SearchService_GetJobRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetSearchSuggestions(ctx context.Context, in *SuggestionRequest, opts ...grpc.CallOption) (*SuggestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestionResponse)
	err := c.cc.Invoke(ctx, SearchService_GetSearchSuggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetTrendingSearches(ctx context.Context, in *TrendingRequest, opts ...grpc.CallOption) (*TrendingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrendingResponse)
	err := c.cc.Invoke(ctx, SearchService_GetTrendingSearches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) TriggerCrawl(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrawlResponse)
	err := c.cc.Invoke(ctx, SearchService_TriggerCrawl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyticsResponse)
	err := c.cc.Invoke(ctx, SearchService_GetAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility.
type SearchServiceServer interface {
	// Job Search - Full-text search with filters
	SearchJobs(context.Context, *SearchJobsRequest) (*SearchJobsResponse, error)
	// Resume-Job Matching - Calculate match score
	MatchResumeToJob(context.Context, *MatchRequest) (*MatchResponse, error)
	// Batch Matching - Parallel matching for multiple jobs
	BatchMatch(context.Context, *BatchMatchRequest) (*BatchMatchResponse, error)
	// Job Recommendations - Personalized job suggestions
	GetJobRecommendations(context.Context, *RecommendRequest) (*RecommendResponse, error)
	// Search Suggestions - Autocomplete
	GetSearchSuggestions(context.Context, *SuggestionRequest) (*SuggestionResponse, error)
	// Trending Searches - Popular searches
	GetTrendingSearches(context.Context, *TrendingRequest) (*TrendingResponse, error)
	// Crawler Control - Trigger job crawling
	TriggerCrawl(context.Context, *CrawlRequest) (*CrawlResponse, error)
	// Analytics - Market data aggregation
	GetAnalytics(context.Context, *AnalyticsRequest) (*AnalyticsResponse, error)
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServiceServer struct{}

func (UnimplementedSearchServiceServer) SearchJobs(context.Context, *SearchJobsRequest) (*SearchJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchJobs not implemented")
}
func (UnimplementedSearchServiceServer) MatchResumeToJob(context.Context, *MatchRequest) (*MatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MatchResumeToJob not implemented")
}
func (UnimplementedSearchServiceServer) BatchMatch(context.Context, *BatchMatchRequest) (*BatchMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchMatch not implemented")
}
func (UnimplementedSearchServiceServer) GetJobRecommendations(context.Context, *RecommendRequest) (*RecommendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobRecommendations not implemented")
}
func (UnimplementedSearchServiceServer) GetSearchSuggestions(context.Context, *SuggestionRequest) (*SuggestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSearchSuggestions not implemented")
}
func (UnimplementedSearchServiceServer) GetTrendingSearches(context.Context, *TrendingRequest) (*TrendingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrendingSearches not implemented")
}
func (UnimplementedSearchServiceServer) TriggerCrawl(context.Context, *CrawlRequest) (*CrawlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerCrawl not implemented")
}
func (UnimplementedSearchServiceServer) GetAnalytics(context.Context, *AnalyticsRequest) (*AnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnalytics not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}
func (UnimplementedSearchServiceServer) testEmbeddedByValue()                       {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	// If the following call panics, it indicates UnimplementedSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_SearchJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchJobs(ctx, req.(*SearchJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_MatchResumeToJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).MatchResumeToJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_MatchResumeToJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).MatchResumeToJob(ctx, req.(*MatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_BatchMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).BatchMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_BatchMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).BatchMatch(ctx, req.(*BatchMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetJobRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetJobRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetJobRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetJobRecommendations(ctx, req.(*RecommendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetSearchSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetSearchSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetSearchSuggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetSearchSuggestions(ctx, req.(*SuggestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetTrendingSearches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetTrendingSearches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetTrendingSearches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetTrendingSearches(ctx, req.(*TrendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_TriggerCrawl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).TriggerCrawl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_TriggerCrawl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).TriggerCrawl(ctx, req.(*CrawlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetAnalytics(ctx, req.(*AnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cvibe.search.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchJobs",
			Handler:    _SearchService_SearchJobs_Handler,
		},
		{
			MethodName: "MatchResumeToJob",
			Handler:    _SearchService_MatchResumeToJob_Handler,
		},
		{
			MethodName: "BatchMatch",
			Handler:    _SearchService_BatchMatch_Handler,
		},
		{
			MethodName: "GetJobRecommendations",
			Handler:    _SearchService_GetJobRecommendations_Handler,
		},
		{
			MethodName: "GetSearchSuggestions",
			Handler:    _SearchService_GetSearchSuggestions_Handler,
		},
		{
			MethodName: "GetTrendingSearches",
			Handler:    _SearchService_GetTrendingSearches_Handler,
		},
		{
			MethodName: "TriggerCrawl",
			Handler:    _SearchService_TriggerCrawl_Handler,
		},
		{
			MethodName: "GetAnalytics",
			Handler:    _SearchService_GetAnalytics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search_service.proto",
}
