package com.cvibe.biz.resume.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Summary DTO for resume builder dashboard
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ResumeBuilderSummary {

    /**
     * Total resumes generated by user
     */
    private long totalGenerations;

    /**
     * Total exported resumes
     */
    private long exportedCount;

    /**
     * Number of custom templates created
     */
    private long customTemplates;

    /**
     * Most targeted companies
     */
    private List<String> topCompanies;

    /**
     * Recent generations
     */
    private List<GeneratedResumeDto> recentGenerations;

    /**
     * Featured templates for quick start
     */
    private List<ResumeTemplateDto> featuredTemplates;
}
